update cmake of traffic signal messages
tier4/autoware_auto_msgs pull request #22
Opened 2021-11-11 15:31 UTC by takayuki5168

update cmake of traffic signal messages for https://github.com/tier4/autoware_auto_msgs/pull/21

2021-11-11 15:32 UTC, takayuki5168 commented
@taichiH We forgot to update CMakeLists.txt, sorry

2021-11-11 15:38 UTC, taichiH approved these changes
sorry... I forgot to commit CMakeLists.txt.

2021-11-11 15:40 UTC, taichiH requested changes

2021-11-11 15:40 UTC, taichiH commented on autoware_auto_perception_msgs/CMakeLists.txt
> +  "msg/LookingTrafficSignal.idl"
please sort alphabetically

2021-11-11 15:40 UTC, takayuki5168 commented
Once build failed. I don't know why but I jsut reopened this PR
https://github.com/tier4/autoware_auto_msgs/runs/4179826814?check_suite_focus=true

2021-11-11 15:47 UTC, takayuki5168 commented on autoware_auto_perception_msgs/CMakeLists.txt
> +  "msg/LookingTrafficSignal.idl"
https://github.com/tier4/autoware_auto_msgs/pull/22/commits/8af155a4667d3b585898b80693a9229f72e78220

2021-11-11 15:50 UTC, takayuki5168 commented
![image](https://user-images.githubusercontent.com/20228327/141327607-082611d9-e8d0-45c2-9cef-b95b8318a86a.png)
Still build failed...

2021-11-11 15:51 UTC, takayuki5168 commented
It seems final is pre-defined word in C++, and fail formatting? :thinki

2021-11-11 15:52 UTC, takayuki5168 commented
cc @kenji-miyake

2021-11-11 16:24 UTC, taichiH commented
@takayuki5168 @satoshi-ota 
`final` is a reserved word, so when I changed it, the test passed on my local environment.
How about changing to other word? (result?)

https://github.com/tier4/autoware_auto_msgs/blob/0f87daa6f06d0c0513a502d0e192be113181692a/autoware_auto_perception_msgs/msg/LookingTrafficSignal.idl#L11

2021-11-11 16:26 UTC, takayuki5168 commented
@tkimura4 ↑

2021-11-12 01:32 UTC, takayuki5168 commented
@taichiH Everyone accepts the idea to renaming to `result`. Could you approve again and merge.

2021-11-12 01:32 UTC, taichiH approved these changes

2021-11-12 01:40 UTC, merged